name: My First CI Pipeline

on: push

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello Atique! Your pipeline is working! 🚀"

      - name: Show date and time
        run: date

      - name: List files in repo
        run: ls -la




